"""Regenerate PROBLEMS.md from the YAML frontmatter in every problems/*/question.md.

Run from repo root:
    python3 scripts/build_index.py            # rewrite PROBLEMS.md
    python3 scripts/build_index.py --check    # exit 1 if PROBLEMS.md is stale

Frontmatter contract (each problems/NNN-slug/question.md must start with):

    ---
    id: 21
    title: Data Platform for an Electricity Retailer
    category: System Design
    topics: [smart meter, IoT, warehouse, batch]
    difficulty: Hard
    solution: solution.md
    ---
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PROBLEMS_DIR = REPO / "problems"
INDEX = REPO / "PROBLEMS.md"

CATEGORY_LEGEND = [
    ("SQL & Querying",          "Writing, reading and reasoning about SQL like a senior engineer"),
    ("Data Modeling",           "Star schemas, history tracking, grain, dimensions, SCDs"),
    ("Database Internals",      "Engines, ACID, isolation levels, indexes, B-tree vs LSM, normalization"),
    ("Database Operations",     "Running databases at scale: replicas, sharding, connection pools, deadlocks"),
    ("Batch Pipelines",         "ETL/ELT, idempotency, data cleaning, contracts, orchestration"),
    ("Streaming",               "Kafka, watermarks, exactly-once, ordering, consumer lag"),
    ("Storage & Formats",       "Parquet, lakehouse, partitioning, clustering, materialized views"),
    ("System Design",           "End-to-end pipelines for real consumer and energy-sector products"),
    ("Cloud Services",          "Picking between AWS, GCP and Azure services with clear trade-offs"),
    ("Cost Optimization",       "Finding waste in queries, jobs, and infrastructure when the bill spikes"),
    ("Debugging & Reliability", "Step-by-step investigation when the number is wrong or the job died"),
    ("People & Process",        "Mentoring, comms, postmortems, ownership, rollouts"),
]


def parse_frontmatter(path: Path) -> dict:
    text = path.read_text()
    if not text.startswith("---\n"):
        raise SystemExit(f"{path}: missing frontmatter")
    end = text.find("\n---\n", 4)
    if end == -1:
        raise SystemExit(f"{path}: unterminated frontmatter")
    block = text[4:end]
    meta: dict = {}
    for line in block.splitlines():
        if not line.strip() or ":" not in line:
            continue
        key, _, val = line.partition(":")
        meta[key.strip()] = val.strip()
    meta["id"] = int(meta["id"])
    topics = meta.get("topics", "[]").strip()
    if topics.startswith("[") and topics.endswith("]"):
        topics = topics[1:-1]
    meta["topics"] = [t.strip() for t in topics.split(",") if t.strip()]
    # Optional ordering and interview fields, added in restructure wave 1.
    if "learn_order" in meta:
        try:
            meta["learn_order"] = int(meta["learn_order"])
        except ValueError:
            meta["learn_order"] = None
    return meta


def load_all() -> list[dict]:
    rows = []
    for folder in sorted(PROBLEMS_DIR.iterdir()):
        if not folder.is_dir():
            continue
        q = folder / "question.md"
        if not q.exists():
            continue
        meta = parse_frontmatter(q)
        meta["folder"] = folder.name
        rows.append(meta)
    rows.sort(key=lambda r: r["id"])
    return rows


def render(rows: list[dict]) -> str:
    lines = [
        "# Problems Index",
        "",
        "A quick overview of every problem in this repo. Use the **Category** and **Topics** columns to filter by what you want to practice. Each row links to the problem statement and the reference solution.",
        "",
        "> This file is generated by `scripts/build_index.py` from the frontmatter in each problem's `question.md`. Do not edit by hand.",
        "",
        "| #  | Problem | Category | Difficulty | Interview | Question | Solution |",
        "|----|---------|----------|------------|-----------|----------|----------|",
    ]
    for r in rows:
        folder = r["folder"]
        sol = r.get("solution", "solution.md")
        iv = r.get("interview_value", "")
        iv_mark = {"must-have": "⭐ must", "strong": "strong", "optional": "optional"}.get(iv, "")
        lines.append(
            f"| {r['id']} | {r['title']} | {r['category']} | {r['difficulty']} | {iv_mark} | "
            f"[Question](problems/{folder}/question.md) | "
            f"[Solution](problems/{folder}/{sol}) |"
        )

    lines += ["", "---", "", "### Category Legend", "",
              "| Category | What you practice |",
              "|----------|-------------------|"]
    used = {r["category"] for r in rows}
    for cat, desc in CATEGORY_LEGEND:
        if cat in used:
            lines.append(f"| {cat} | {desc} |")

    lines += [
        "",
        "### Difficulty Guide",
        "",
        "* **Easy** — A focused warm-up. Solvable or explainable in under an hour.",
        "* **Medium** — Realistic interview question. Has edge cases that matter.",
        "* **Hard** — Multi-step or system-design heavy. Closer to a take-home task.",
        "",
        "### Interview Value",
        "",
        "* **⭐ must** — Shows up in the majority of senior data engineer interview loops right now.",
        "* **strong** — Common follow-up territory. Worth knowing cold for a senior bar.",
        "* **optional** — Niche, situational, or domain-specific. Read when curious.",
        "",
    ]

    # Interview must-haves quick reference, sorted by learn_order
    must_haves = sorted(
        (r for r in rows if r.get("interview_value") == "must-have"),
        key=lambda r: r.get("learn_order") or 9999,
    )
    if must_haves:
        lines += [
            "---",
            "",
            "### ⭐ Interview Must-Haves",
            "",
            "Twenty-nine problems that cover the questions you cannot dodge in a senior data engineer loop. Read them in the order shown, top to bottom.",
            "",
        ]
        for r in must_haves:
            order = r.get("learn_order")
            prefix = f"{order}. " if order else "- "
            lines.append(f"{prefix}[{r['title']}](problems/{r['folder']}/question.md) — *{r['category']}*")
        lines.append("")

    # Recommended reading order, sorted by learn_order
    ordered = sorted(
        (r for r in rows if r.get("learn_order") is not None),
        key=lambda r: r["learn_order"],
    )
    if ordered:
        lines += [
            "---",
            "",
            "### Recommended Reading Order",
            "",
            "All 75 problems arranged as a pedagogical sequence. Read top to bottom for a complete path from SQL to senior-level data engineering.",
            "",
        ]
        for r in ordered:
            lines.append(
                f"{r['learn_order']}. [{r['title']}](problems/{r['folder']}/question.md) "
                f"— *{r['category']}*, {r['difficulty']}"
            )
        lines.append("")

    lines += [
        "> New problems are added regularly. If you want to contribute, see the [Contribution Guide](CONTRIBUTION.md).",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    check = "--check" in argv
    rows = load_all()
    if len(rows) != len({r["id"] for r in rows}):
        raise SystemExit("Duplicate problem ids detected")

    new = render(rows)
    if check:
        current = INDEX.read_text() if INDEX.exists() else ""
        if current != new:
            print("PROBLEMS.md is stale. Run: python3 scripts/build_index.py", file=sys.stderr)
            return 1
        print("PROBLEMS.md is up to date.")
        return 0

    INDEX.write_text(new)
    print(f"Wrote {INDEX.relative_to(REPO)} ({len(rows)} problems).")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
