"""Regenerate PROBLEMS.md from the YAML frontmatter in every problems/*/question.md.

Run from repo root:
    python3 scripts/build_index.py            # rewrite PROBLEMS.md
    python3 scripts/build_index.py --check    # exit 1 if PROBLEMS.md is stale

Frontmatter contract (each problems/NNN-slug/question.md must start with):

    ---
    id: 21
    title: Data Platform for an Electricity Retailer
    category: System Design
    topics: [smart meter, IoT, warehouse, batch]
    difficulty: Hard
    solution: solution.md
    ---
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PROBLEMS_DIR = REPO / "problems"
INDEX = REPO / "PROBLEMS.md"

CATEGORY_LEGEND = [
    ("Logs and Monitoring", "Parsing and analyzing large log files, counting events, ranking"),
    ("Streaming",           "Continuous data, rolling stats, watermarks, ordering, lag"),
    ("Data Cleaning",       "Validating, normalizing and rejecting bad rows from raw files"),
    ("Schema Validation",   "Handling evolving JSON or Avro schemas without breaking consumers"),
    ("Data Integration",    "Combining data from many sources with different shapes and conventions"),
    ("Fundamentals",        "Core concepts every data engineer should be able to explain plainly"),
    ("SQL Thinking",        "Writing, reading and reasoning about SQL like a senior engineer"),
    ("System Design",       "End-to-end pipelines for real consumer and energy-sector products"),
    ("Scenarios",           "Tricky real-life situations that test judgement and communication"),
    ("Cloud Decisions",     "Picking between AWS / GCP services with clear trade-offs"),
    ("Data Modeling",       "Star schemas, history tracking, grain, dimensions"),
    ("Debugging",           "Step-by-step investigation of \"the number is wrong\" style problems"),
    ("Cost & Performance",  "Finding waste in queries, jobs, and infrastructure"),
    ("People & Process",    "Mentoring, comms, postmortems, ownership, rollouts"),
]


def parse_frontmatter(path: Path) -> dict:
    text = path.read_text()
    if not text.startswith("---\n"):
        raise SystemExit(f"{path}: missing frontmatter")
    end = text.find("\n---\n", 4)
    if end == -1:
        raise SystemExit(f"{path}: unterminated frontmatter")
    block = text[4:end]
    meta: dict = {}
    for line in block.splitlines():
        if not line.strip() or ":" not in line:
            continue
        key, _, val = line.partition(":")
        meta[key.strip()] = val.strip()
    meta["id"] = int(meta["id"])
    topics = meta.get("topics", "[]").strip()
    if topics.startswith("[") and topics.endswith("]"):
        topics = topics[1:-1]
    meta["topics"] = [t.strip() for t in topics.split(",") if t.strip()]
    return meta


def load_all() -> list[dict]:
    rows = []
    for folder in sorted(PROBLEMS_DIR.iterdir()):
        if not folder.is_dir():
            continue
        q = folder / "question.md"
        if not q.exists():
            continue
        meta = parse_frontmatter(q)
        meta["folder"] = folder.name
        rows.append(meta)
    rows.sort(key=lambda r: r["id"])
    return rows


def render(rows: list[dict]) -> str:
    lines = [
        "# Problems Index",
        "",
        "A quick overview of every problem in this repo. Use the **Category** and **Topics** columns to filter by what you want to practice. Each row links to the problem statement and the reference solution.",
        "",
        "> This file is generated by `scripts/build_index.py` from the frontmatter in each problem's `question.md`. Do not edit by hand.",
        "",
        "| #  | Problem | Category | Topics | Difficulty | Question | Solution |",
        "|----|---------|----------|--------|------------|----------|----------|",
    ]
    for r in rows:
        topics = ", ".join(r["topics"])
        folder = r["folder"]
        sol = r.get("solution", "solution.md")
        lines.append(
            f"| {r['id']} | {r['title']} | {r['category']} | {topics} | {r['difficulty']} | "
            f"[Question](problems/{folder}/question.md) | "
            f"[Solution](problems/{folder}/{sol}) |"
        )

    lines += ["", "---", "", "### Category Legend", "",
              "| Category | What you practice |",
              "|----------|-------------------|"]
    used = {r["category"] for r in rows}
    for cat, desc in CATEGORY_LEGEND:
        if cat in used:
            lines.append(f"| {cat} | {desc} |")

    lines += [
        "",
        "### Difficulty Guide",
        "",
        "* **Easy** — A focused warm-up. Solvable or explainable in under an hour.",
        "* **Medium** — Realistic interview question. Has edge cases that matter.",
        "* **Hard** — Multi-step or system-design heavy. Closer to a take-home task.",
        "",
        "> New problems are added regularly. If you want to contribute, see the [Contribution Guide](CONTRIBUTION.md).",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    check = "--check" in argv
    rows = load_all()
    if len(rows) != len({r["id"] for r in rows}):
        raise SystemExit("Duplicate problem ids detected")

    new = render(rows)
    if check:
        current = INDEX.read_text() if INDEX.exists() else ""
        if current != new:
            print("PROBLEMS.md is stale. Run: python3 scripts/build_index.py", file=sys.stderr)
            return 1
        print("PROBLEMS.md is up to date.")
        return 0

    INDEX.write_text(new)
    print(f"Wrote {INDEX.relative_to(REPO)} ({len(rows)} problems).")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
